require('./config/env');
const mongoose = require('mongoose');
const Test = require('./models/Test');
const Question = require('./models/Question');
const User = require('./models/User');

const connectDB = async () => {
  const uri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/placement_portal';
  await mongoose.connect(uri);
  console.log('MongoDB Connected for Mock Test Seeding');
};

const EXTRA_QUESTIONS = [
  // --- REASONING QUESTIONS ---
  {
    topic: 'Number Series',
    moduleType: 'Reasoning',
    question: 'Find the next number in the series: 3, 7, 15, 31, 63, ?',
    options: ['95', '127', '125', '128'],
    correctAnswer: '127',
    explanation: 'Each term is generated by (previous * 2) + 1. 63 * 2 + 1 = 127.',
    difficulty: 'Easy'
  },
  {
    topic: 'Coding Decoding',
    moduleType: 'Reasoning',
    question: 'If "APPLE" is coded as "EQTPI", then how is "ORANGE" coded in the same language?',
    options: ['SVETKI', 'STEOJF', 'SUESKI', 'SVERKH'],
    correctAnswer: 'SVETKI',
    explanation: 'Each letter is shifted by +4 in alphabetical position.',
    difficulty: 'Medium'
  },
  {
    topic: 'Blood Relations',
    moduleType: 'Reasoning',
    question: 'Pointing to a photograph, Rahul said, "She is the daughter of my grandfather\'s only son." How is the woman related to Rahul?',
    options: ['Mother', 'Sister', 'Aunt', 'Cousin'],
    correctAnswer: 'Sister',
    explanation: 'Grandfather\'s only son is Rahul\'s father. The daughter of Rahul\'s father is Rahul\'s sister.',
    difficulty: 'Easy'
  },
  {
    topic: 'Direction Sense',
    moduleType: 'Reasoning',
    question: 'A man walks 5 km North, turns right and walks 3 km, then turns right again and walks 5 km. How far is he from his starting point?',
    options: ['3 km East', '5 km South', '8 km North', '3 km West'],
    correctAnswer: '3 km East',
    explanation: 'The north and south movements cancel out (5km - 5km = 0), leaving a net displacement of 3 km East.',
    difficulty: 'Easy'
  },
  {
    topic: 'Syllogism',
    moduleType: 'Reasoning',
    question: 'Statements: All cats are dogs. Some dogs are birds. Conclusions: I. Some cats are birds. II. Some birds are dogs.',
    options: ['Only I follows', 'Only II follows', 'Both I and II follow', 'Neither follows'],
    correctAnswer: 'Only II follows',
    explanation: 'Since Some dogs are birds, by conversion Some birds are dogs (II follows). There is no direct intersection established between cats and birds.',
    difficulty: 'Medium'
  },
  {
    topic: 'Seating Arrangement',
    moduleType: 'Reasoning',
    question: 'Five friends A, B, C, D, E are sitting in a row facing North. C is sitting in the middle. A is to the immediate left of C. E is at the extreme right. Who is sitting to the immediate right of C?',
    options: ['A', 'B', 'D', 'Cannot be determined without more info'],
    correctAnswer: 'Cannot be determined without more info',
    explanation: 'Either B or D could be in the position immediately right of C unless their relative positions are defined.',
    difficulty: 'Medium'
  },
  {
    topic: 'Clock & Calendar',
    moduleType: 'Reasoning',
    question: 'What is the angle between the hour and minute hands of a clock at 3:30?',
    options: ['75°', '85°', '90°', '70°'],
    correctAnswer: '75°',
    explanation: 'Angle = |(30 * H) - (5.5 * M)| = |(30 * 3) - (5.5 * 30)| = |90 - 165| = 75°.',
    difficulty: 'Medium'
  },
  {
    topic: 'Puzzles',
    moduleType: 'Reasoning',
    question: 'In a certain code, 134 means "good and tasty", 478 means "see good pictures", and 729 means "pictures are faint". Which digit stands for "see"?',
    options: ['4', '7', '8', '9'],
    correctAnswer: '8',
    explanation: 'In 134 and 478, common word is "good" and digit is 4. In 478 and 729, common word is "pictures" and digit is 7. Thus in 478, "see" corresponds to 8.',
    difficulty: 'Medium'
  },
  {
    topic: 'Analogies',
    moduleType: 'Reasoning',
    question: 'Odometer is to Mileage as Compass is to:',
    options: ['Speed', 'Hiking', 'Needle', 'Direction'],
    correctAnswer: 'Direction',
    explanation: 'An odometer measures mileage; a compass determines direction.',
    difficulty: 'Easy'
  },
  {
    topic: 'Statement & Assumptions',
    moduleType: 'Reasoning',
    question: 'Statement: "The government has decided to provide free internet to all colleges." Assumption: I. Most students will benefit from internet access. II. College students only use internet for studies.',
    options: ['Only I is implicit', 'Only II is implicit', 'Both are implicit', 'Neither is implicit'],
    correctAnswer: 'Only I is implicit',
    explanation: 'The policy assumes internet access provides general student utility, not that it will be exclusively restricted to study only.',
    difficulty: 'Medium'
  },

  // --- VERBAL ENGLISH QUESTIONS ---
  {
    topic: 'Spotting Errors',
    moduleType: 'English',
    question: 'Identify the segment with grammatical error: "Neither of the two candidates (A) / have submitted (B) / their application form (C) / on time (D)."',
    options: ['A', 'B', 'C', 'D'],
    correctAnswer: 'B',
    explanation: '"Neither" is singular, so it must take the singular verb "has submitted" instead of "have submitted".',
    difficulty: 'Medium'
  },
  {
    topic: 'Synonyms & Antonyms',
    moduleType: 'English',
    question: 'Choose the word that is most opposite in meaning (Antonym) to "METICULOUS":',
    options: ['Careless', 'Diligent', 'Precise', 'Painstaking'],
    correctAnswer: 'Careless',
    explanation: 'Meticulous means showing great attention to detail; careless is its exact antonym.',
    difficulty: 'Easy'
  },
  {
    topic: 'Sentence Correction',
    moduleType: 'English',
    question: 'Choose the correct form: "Hardly had the meeting started ______ the lights went out."',
    options: ['than', 'when', 'then', 'before'],
    correctAnswer: 'when',
    explanation: 'The correlative conjunction "Hardly had..." is always paired with "when".',
    difficulty: 'Medium'
  },
  {
    topic: 'Para Jumbles',
    moduleType: 'English',
    question: 'Arrange the sentences into a coherent paragraph: P: However, renewable sources are gaining traction. Q: Traditional fossil fuels have powered industries for centuries. R: Solar and wind energy lead this transformation. S: This transition is vital for climate preservation.',
    options: ['Q - P - R - S', 'P - Q - R - S', 'Q - R - P - S', 'S - R - P - Q'],
    correctAnswer: 'Q - P - R - S',
    explanation: 'Q introduces traditional fuels, P transitions with "However", R specifies the renewable leaders, and S concludes the significance.',
    difficulty: 'Medium'
  },
  {
    topic: 'Idioms and Phrases',
    moduleType: 'English',
    question: 'What is the meaning of the idiom "To burn the midnight oil"?',
    options: ['To waste electricity', 'To work or study late into the night', 'To cause destruction', 'To wake up early in the morning'],
    correctAnswer: 'To work or study late into the night',
    explanation: '"Burning the midnight oil" refers to working or studying late into the night.',
    difficulty: 'Easy'
  },
  {
    topic: 'Reading Comprehension',
    moduleType: 'English',
    question: 'The passage highlights that machine learning models depend on high-quality training datasets. What can be inferred if a dataset is biased?',
    options: ['The model will achieve 100% accuracy', 'The model predictions will perpetuate those biases', 'The algorithm will automatically correct the data', 'The hardware will fail'],
    correctAnswer: 'The model predictions will perpetuate those biases',
    explanation: 'Biased training data causes the resulting ML model to internalize and reproduce systematic bias.',
    difficulty: 'Medium'
  },
  {
    topic: 'Fill in the Blanks',
    moduleType: 'English',
    question: 'The company was praised for its ______ approach to environmental sustainability.',
    options: ['proactive', 'negligent', 'reluctant', 'superficial'],
    correctAnswer: 'proactive',
    explanation: '"Proactive" describes taking positive initiative in advance, fitting the context of praise.',
    difficulty: 'Easy'
  },
  {
    topic: 'Direct and Indirect Speech',
    moduleType: 'English',
    question: 'Convert to indirect speech: She said, "I am reading an interesting book."',
    options: [
      'She said that she is reading an interesting book.',
      'She said that she was reading an interesting book.',
      'She said that she had read an interesting book.',
      'She told that I was reading an interesting book.'
    ],
    correctAnswer: 'She said that she was reading an interesting book.',
    explanation: 'Present continuous tense ("am reading") changes to past continuous ("was reading") in reported speech.',
    difficulty: 'Medium'
  },
  {
    topic: 'Active and Passive Voice',
    moduleType: 'English',
    question: 'Convert to passive voice: "The manager approved the new budget."',
    options: [
      'The new budget was approved by the manager.',
      'The new budget is approved by the manager.',
      'The new budget has been approved by the manager.',
      'The manager was approving the new budget.'
    ],
    correctAnswer: 'The new budget was approved by the manager.',
    explanation: 'Simple past active ("approved") becomes simple past passive ("was approved").',
    difficulty: 'Easy'
  },
  {
    topic: 'One Word Substitution',
    moduleType: 'English',
    question: 'A person who speaks many languages is called a:',
    options: ['Polyglot', 'Philanthropist', 'Polygraph', 'Omniscient'],
    correctAnswer: 'Polyglot',
    explanation: 'A polyglot is someone who knows and is able to use several languages.',
    difficulty: 'Easy'
  }
];

const MOCK_TESTS_CONFIG = [
  {
    title: 'TCS NQT National Mock Test',
    slug: 'tcs-nqt-national-mock-test',
    category: 'company',
    description: 'Comprehensive 50-Question assessment mirroring the official TCS NQT recruitment test pattern with Quantitative, Logical Reasoning, and Verbal Ability sections.',
    duration: 60,
    totalQuestions: 50,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    passingPercentage: 60,
    companyTags: ['TCS', 'Tata Consultancy Services', 'TCS NQT', 'TCS Ninja', 'TCS Digital'],
    moduleTypes: ['Aptitude', 'Reasoning', 'English'],
    colorScheme: 'indigo',
    instructions: [
      'Total duration: 60 minutes for 50 questions.',
      'Each correct answer carries +1 mark.',
      'Negative marking: 0.25 marks will be deducted for every incorrect attempt.',
      'Unattempted questions carry 0 marks.',
      'The test will automatically submit when the timer expires.'
    ]
  },
  {
    title: 'Quantitative Aptitude Grand Mock Test',
    slug: 'quantitative-aptitude-grand-mock-test',
    category: 'aptitude',
    description: 'Complete high-yield aptitude mock covering arithmetic, algebra, percentages, profit & loss, time-speed-distance, and probability.',
    duration: 45,
    totalQuestions: 30,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    passingPercentage: 65,
    companyTags: ['Infosys', 'TCS', 'Wipro', 'Capgemini'],
    moduleTypes: ['Aptitude'],
    colorScheme: 'blue',
    instructions: [
      'Duration: 45 minutes for 30 questions.',
      'Covers core quantitative mathematics used in campus recruitment screenings.',
      '+1 mark for correct, -0.25 for incorrect.'
    ]
  },
  {
    title: 'Logical & Analytical Reasoning Speed Test',
    slug: 'logical-analytical-reasoning-speed-test',
    category: 'reasoning',
    description: 'Fast-paced reasoning test focusing on number series, syllogisms, blood relations, seating arrangements, and directional puzzles.',
    duration: 45,
    totalQuestions: 30,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    passingPercentage: 60,
    companyTags: ['Accenture', 'Cognizant', 'Deloitte'],
    moduleTypes: ['Reasoning', 'Aptitude'],
    colorScheme: 'purple',
    instructions: [
      'Duration: 45 minutes.',
      'Test your analytical deduction and logical pattern speed.',
      'Auto-submission enabled.'
    ]
  },
  {
    title: 'Verbal Ability & English Placement Mock',
    slug: 'verbal-ability-english-placement-mock',
    category: 'english',
    description: 'Assess grammatical precision, vocabulary, reading comprehension, para-jumbles, and error spotting for campus interviews.',
    duration: 30,
    totalQuestions: 30,
    negativeMarking: 0.25,
    difficulty: 'Easy',
    passingPercentage: 70,
    companyTags: ['TCS', 'Infosys', 'Wipro', 'Tech Mahindra'],
    moduleTypes: ['English', 'Aptitude'],
    colorScheme: 'rose',
    instructions: [
      'Duration: 30 minutes.',
      'Focus on grammar rules, idioms, vocabulary, and reading comprehension.',
      '+1 mark per correct answer, -0.25 for wrong.'
    ]
  },
  {
    title: 'Infosys DSE / SE Assessment',
    slug: 'infosys-dse-se-assessment',
    category: 'company',
    description: 'Standardized assessment reflecting the latest Infosys pseudo-code, mathematical ability, and puzzle solving recruitment rounds.',
    duration: 60,
    totalQuestions: 40,
    negativeMarking: 0.25,
    difficulty: 'Hard',
    passingPercentage: 65,
    companyTags: ['Infosys', 'DSE', 'SP', 'Specialist Programmer'],
    moduleTypes: ['Aptitude', 'Reasoning'],
    colorScheme: 'emerald',
    instructions: [
      'Duration: 60 minutes for 40 questions.',
      'Higher difficulty mathematical and logical problem solving.'
    ]
  },
  {
    title: 'Cognizant GenC Elevate Assessment',
    slug: 'cognizant-genc-elevate-assessment',
    category: 'company',
    description: 'Cognizant recruitment pattern test with analytical reasoning, quantitative problem solving, and verbal English skills.',
    duration: 60,
    totalQuestions: 40,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    passingPercentage: 60,
    companyTags: ['Cognizant', 'GenC', 'GenC Elevate', 'GenC Next'],
    moduleTypes: ['Aptitude', 'Reasoning', 'English'],
    colorScheme: 'cyan',
    instructions: [
      'Duration: 60 minutes for 40 questions.',
      'Comprehensive aptitude and reasoning speed test.'
    ]
  },
  {
    title: 'Wipro Elite NLTH National Test',
    slug: 'wipro-elite-nlth-national-test',
    category: 'company',
    description: 'National level test simulation for Wipro Elite NLTH hiring including quantitative aptitude, logical reasoning, and verbal comprehension.',
    duration: 60,
    totalQuestions: 40,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    passingPercentage: 60,
    companyTags: ['Wipro', 'Elite NLTH', 'Wipro Turbo'],
    moduleTypes: ['Aptitude', 'Reasoning', 'English'],
    colorScheme: 'amber',
    instructions: [
      'Duration: 60 minutes for 40 questions.',
      'Includes balanced distribution of Quantitative, Logical, and Verbal questions.'
    ]
  },
  {
    title: 'Accenture Placement Readiness Mock',
    slug: 'accenture-placement-readiness-mock',
    category: 'company',
    description: 'Accenture assessment pattern featuring critical reasoning, abstract reasoning, quantitative calculations, and technical verbal skills.',
    duration: 50,
    totalQuestions: 35,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    passingPercentage: 65,
    companyTags: ['Accenture', 'ASE', 'FADA'],
    moduleTypes: ['Aptitude', 'Reasoning', 'English'],
    colorScheme: 'violet',
    instructions: [
      'Duration: 50 minutes for 35 questions.',
      'Critical thinking and speed assessment.'
    ]
  }
];

async function seedMockTests() {
  try {
    await connectDB();
    console.log('--- STARTING MOCK TEST MODULE SEEDING ---');

    // 1. Seed Extra Questions if not present
    console.log('Upserting Reasoning and English Questions pool...');
    for (const q of EXTRA_QUESTIONS) {
      await Question.findOneAndUpdate(
        { questionText: q.question },
        {
          questionText: q.question,
          category: q.topic,
          topic: q.topic,
          moduleType: q.moduleType,
          options: q.options,
          correctAnswer: q.correctAnswer,
          explanation: q.explanation,
          difficulty: q.difficulty,
          isPublished: true
        },
        { upsert: true, returnDocument: 'after' }
      );
    }

    // Get all available questions from MongoDB
    const allQuestions = await Question.find();
    console.log(`Available Question pool size: ${allQuestions.length} MCQs`);

    if (allQuestions.length === 0) {
      throw new Error('No questions available in database to seed tests.');
    }

    // 2. Seed Mock Tests
    console.log(`Seeding ${MOCK_TESTS_CONFIG.length} Standardized Placement Mock Tests...`);

    for (let i = 0; i < MOCK_TESTS_CONFIG.length; i++) {
      const cfg = MOCK_TESTS_CONFIG[i];
      
      // Select questions matching moduleTypes or diverse distribution
      const matchingQuestions = allQuestions.filter(q => 
        !cfg.moduleTypes || cfg.moduleTypes.length === 0 || cfg.moduleTypes.includes(q.moduleType)
      );

      const pool = matchingQuestions.length >= cfg.totalQuestions ? matchingQuestions : allQuestions;
      
      // Shuffle & pick totalQuestions
      const shuffled = [...pool].sort(() => 0.5 - Math.random());
      const selectedQuestions = shuffled.slice(0, cfg.totalQuestions).map(q => q._id);

      const testDoc = await Test.findOneAndUpdate(
        { slug: cfg.slug },
        {
          ...cfg,
          totalMarks: cfg.totalQuestions,
          questions: selectedQuestions,
          isPublished: true
        },
        { upsert: true, returnDocument: 'after' }
      );

      console.log(`✓ Seeded Test: "${testDoc.title}" (${testDoc.questions.length} questions, ${testDoc.duration} mins)`);
    }

    console.log('\n🎉 ALL MOCK TESTS SEEDED SUCCESSFULLY!\n');
    await mongoose.connection.close();
    process.exit(0);
  } catch (err) {
    console.error('Error seeding mock tests:', err);
    process.exit(1);
  }
}

seedMockTests();
